displayName: JWT Field as Header
type: middleware
iconPath: .assets/icon.png

import: github.com/birotaio/traefik-plugins

summary: 'Make custom header from JWT data, can be used for user-based ratelimiting'

testData:
  jwtHeaderName: X-ApiKey
  jwtField: customer_id
  valueHeaderName: X-UserId-RateLimit
  fallbacks:
    - type: ip
  debug: true

